services:
  - type: web
    name: collegestocks-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MONGODB_URI
        sync: false
      - key: FLASK_ENV
        value: production 
